language: python
python:
  - "3.5.6"

before_install:
  - python3 --version
  - pip3 install -U pip
  - pip3 install -U pytest
install:
  - pip3 install -r requirements.txt
# # command to run tests
jobs:
  include:
    - stage: unit tests
      script: pytest
      #script: python3 manage.py test
      
    - stage: test deployment
      script: 'curl http://micro-donations-cs3240.herokuapp.com'
      
      
    #- stage: test
      #script: 'curl https://micro-donations-cs3240.herokuapp.com/'
    # - stage: deploy to staging
    #   script: skip
    #   deploy: &heroku
    #     provider: heroku
    #     app: sf-stages-staging
    #     api_key: $HEROKU_AUTH_TOKEN
    #     on: sf-stages-demo
