language: python
python:
<<<<<<< HEAD
  - "3.5.6"

before_install:
  - python3 --version
  - pip3 install -U pip
  - pip3 install -U pytest
install:
  - pip3 install -r requirements.txt
# # command to run tests
jobs:
  include:
    - stage: unit tests
      script: pytest

    # - stage: deploy to staging
    #   script: skip
    #   deploy: &heroku
    #     provider: heroku
    #     app: sf-stages-staging
    #     api_key: $HEROKU_AUTH_TOKEN
    #     on: sf-stages-demo
#     - stage: test
#        script: 'https://micro-donations-cs3240.herokuapp.com/'

=======
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - pytest
>>>>>>> development
